services:
  postgres:
    container_name: postgres-sql-ecom
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecom
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-ecom
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "username"]
      interval: 30s
      retries: 5

  #ecom-api:
  #  container_name: ecom-api
  #  image: medtahiri01/ecom:latest
  #  ports:
  #    - 8088:8088
  #  networks:
  #    - spring-ecom
  #  depends_on:
  #    - postgres
  #  environment:
  #    - DB_URL=jdbc:postgresql://postgres:5432/ecom

  mail-dev:
    container_name: mail-dev-ecom
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  spring-ecom:
    driver: bridge

volumes:
  postgres:
    driver: local
