services:
  postgres:
    container_name: postgres-sql-ecom
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: ecom
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-ecom
    restart: unless-stopped
  ecom-api:
    container_name: ecom-api
    image: ecom/ecom:1.0.0
    ports:
      - 8088:8088
    networks:
      - spring-ecom
    depends_on:
      - postgres
networks:
  spring-ecom:
    driver: bridge

volumes:
  postgres:
    driver: local