services:
  postgres:
    container_name: postgres-sql-ecom
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecom
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-ecom
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "username"]
      interval: 30s
      retries: 5

  ecom-api:
    container_name: ecom-api
    image: medtahiri01/ecom:latest
    ports:
      - 8088:8088
    networks:
      - spring-ecom
    depends_on:
      - postgres
    restart: unless-stopped

networks:
  spring-ecom:
    driver: bridge

volumes:
  postgres:
    driver: local
