spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
spring-doc:
  default-produces-media-type: application/json
  swagger-ui:
    path: /api-docs
server:
  servlet:
    context-path: /api/v1/